name: cd
on:
  push:
    branches:
    # Limit to the `master` branch
    - master
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy
      run: |
        set -x
        # Install the dependencies of the CRA application and tooling
        npm install
        # Refresh the list of application links to other repositories
        cd cmd/refresh-apps
        npm install
        cd ../..
        node cmd/refresh-apps ${{github.GITHUB_TOKEN}} > apps.json
        cat apps.json
        # Build the CRA application with the refreshed application index
        npm run build
        # Deploy to the application server
        mkdir ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan 172.104.251.140 >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PASSWORD }}" > pass
        sshpass -p $(cat pass) rsync -avh build/ root@172.104.251.140:/var/www/async-await.net --delete
