name: cd
on:
  push:
    branches:
    # Limit to the `master` branch
    - master
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy
      run: |
        set -x
        # Build the CRA application
        #npm install
        #npm run build
        mkdir build
        date -Iseconds >> build/index.html
        # Deploy to the application server
        mkdir ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan 172.104.251.140 >> ~/.ssh/known_hosts
        sshpass -p "{{ secrets.SSH_PASSWORD }}" rsync -avh build/ root@172.104.251.140:/var/www/async-await.net --delete
